### ISSUE TITLE
NuGet GetText.NET.WindowsForms package strictly depends on .Net Framework 4.8

### ISSUE THREAD

**Issue by mcka-dev** [perpetualKid/GetText.NET#18]
Hi,
I can't add `GetText.NET.WindowsForms` package to the old project on .Net Framework 4.7.
![изображение](https://user-images.githubusercontent.com/16173503/99103282-69108080-25f0-11eb-8569-ec5bb700baa8.png)
![изображение](https://user-images.githubusercontent.com/16173503/99103345-7d547d80-25f0-11eb-904d-88cf47e98b27.png)

**Comment by perpetualKid** [comment]
Looks like I were overly optimistic - since GetText.Net.WindowsForms is not able to run on .NET Standard 2.0, looks like I'd set target frameworks to .NET 4.8 and Core 3.1. This is also documented in the dependencies on Nuget:

![image](https://user-images.githubusercontent.com/7158903/99126774-1c846f80-2607-11eb-8e12-7fc36b17fc66.png)

I've just checked, and seems it's possible to target .NET 4.6.1 for GetText.Net.WindowsForms, there is no code requiring higher framework version. 

Build specs will be updated from next prerelease version 0.9.7-beta.1

**Comment by perpetualKid** [comment]
fixed in 0.9.7-beta.1
